README-ja-jp.md

Introduction is not latest version. I update below.
0. Add Note2
0. Add new guideline into common guidelines.

[JP] Update Introduction.

---

README-ja-jp.md

Update parts below.
- Update directory tree.
- Add missing part.
- A small modification for readability.

[JP] Update General

---

README-ja-jp.md

[JP] Add missing Markup

---

README-ja-jp.md

Fix Conflict

---

README-ja-jp.md

Modify sentences and add missing parts in Others.

[JP] Update Others

---

README-ja-jp.md

[JP] Update modules and controllers

---

README-ja-jp.md

[JP] Adjust nuances

---

README-ja-jp.md

Fix translation about domain for Japanese.

Fix translation about domain

---

README.md

Added an explanation about the reason behind controller's naming convention

Added explanation about controller naming convention

---

README.md

Controller's section indentation was really confusing.Take a look at this (before):
http://prntscr.com/70xu60
and after my change:
http://prntscr.com/70xtmh

Fix confusing indentation on a controller section 

---

README.md

Added `controller as`  to controller's section (issue #101)

Feature/controlleras (issue #101)

---

README-ja-jp.md

Update `Controllers` in Japanese. https://github.com/mgechev/angularjs-style-guide/pull/106

[JP]Update Controllers

---

README.md

Issue #102:
1. Added a section for controller + code example
2. Added a section for services + code example

Issue #102 - added data about 'Use Services as your model' + remove business logic from controllers

---

README.md

Code sections weren't align to bullets - this can be confusing.

Align code samples inside services section

---

README.md

Added a 'Performance' section + a first bullet into it (bundle/cache html templates into main js file)

Added a 'Performance' section + a first bullet into it

---

README-ja-jp.md

Update Japanese translation to ad76ac8b16b77cb95c421dedaa91c0cb64514b69.

[ja-jp] Update jp to ad76ac8

---

README.md

Some code snippets were missing the `html` language meaning they were not syntax highlighted.

Added HTML syntax highlighting to HTML blocks.

---

README-zh-cn.md

Update chinese version to lastest version.

Update zh-cn version

---

README.md

error: The app.js file should contains route definitions, configuration
and/or manual bootstrap (if required). - contains
correct: The app.js file should contain route definitions,
configuration and/or manual bootstrap (if required). - contain

docs: Minor fix to Directory structure

---

README-zh-cn.md

Enhance translation: Translate one more un-translated string.

Enhance translation: Translate one more un-translated string.

---

README-it-it.md

TOC links in the italian translation were broke beacuse translation has been done just for the TOC titles, not the links.

Fixed table of content links in the Italian translation

---

README.md

I've added for a better overview a table for the naming convensions

Added table for naming convensions

---

README-de-de.md

Eine Tabelle mit allen Namensgebungen zur besseren Übersicht hinzugefügt

Namensgebung als Tabelle hinzugefügt

---

README.md

replaced every occurrence of "convension" to "convention"
changed "userFiler" to "userFilter"

Updated README.md for typos

---

README.md

Change adminCtrl  to AdminCtrl

Fix the typo

---

README-zh-cn.md

add content change since sep 9 from origin english version to cn version

add content change since sep 9 from origin english version

---

README-fr-fr.md

Added Airbnb Javascript style guide in the fr translation

Added missing link to fr translation

---

README.md

$timeout and $interval lines were duplicated

Removed duplicated lines

---

README-es-es.md

pácticas --> missing "r "
"prácticas" much better

Fix sintaxis

---

README.md

Easier to serialize or deserialize

add $cookie in others section

---

README-ko-kr.md

서비스가 두 개여서 원문을 확인하니 밑이 팩토리

---

README-pt-br.md

Tranlation from the English to the Portuguse, of the paragraph:
> "which is less readable than:"
to: 
> "que é menos legível do que:"

Contributing for translation into Portuguese

---

README-fr-fr.md

Generally updated the structure of the styleguide to better reflect the more up-to-date english one
- Added missing items
- Normalized verb tenses to make the styleguide more consistent
- Correcting many small typos or spelling errors
- Updated code examples

[FR] Updated french styleguide
